version: "3.7"
services: 
  pgsqldb:
    image: postgres:15
    container_name: postgresdb
    #ports:
      #- "15432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - ./pgsqldata:/var/lib/postgresql/data
    networks:
      - app-network

  app:
    image: sappachok/docker-laravel-pgsql-php8
    build: .
    container_name: 'laravelapp'
    #ports:
      #- 8080:80
      #- 8000:8000
      #- 9000:9000
    #working_dir: /var/www
    volumes:
      - ./app:/var/www
      #- ./app_book:/var/www
      #- d://repo//BookStack:/var/www
    restart: unless-stopped
    networks:
      - app-network

  nginx:
    image: nginx:alpine
    #container_name: webserver
    restart: unless-stopped
    tty: true
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./app:/var/www
      #- ./app_book:/var/www
      #- d://repo//BookStack:/var/www
      - ./nginx/conf.d/:/etc/nginx/conf.d/
    links:
      - app
    depends_on:
      - app
    networks:
      - app-network

networks:
  app-network:
    driver: bridge